### ISSUE TITLE
monorepo structure

### ISSUE THREAD

**Issue by sibelius** [welldsagl/create-white-label-app#2]
what about keep each whitelabel variant in a different package inside a monorepo?

**Comment by zuccha** [comment]
What do you mean? You want to keep all white-label configurations inside the same repo, but split into packages?

**Comment by sibelius** [comment]
instead of having scripts, you could save each white label in a different package

**Comment by zuccha** [comment]
Scripts are needed to generate the release package for the apps. The idea is that you always have only one codebase you are working on, from which you can generate the finale products. You don't want to have multiple white-labels.
